apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhWFpzWlhabmNtVm5PbWRvY0Y5aVZtOHdjREpZVlZONVp6QnhlWFp2UVVKU2VqaDBUREZyU21nNVkwZ3pSRkUxYlVrPSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson

